# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_rbern <- function(n, prob) {
    .Call(`_ProductFormFA_cpp_rbern`, n, prob)
}

#' Random generation from BB with Poisson(lambda) mixture
#' 
#' @param alpha value of alpha in product-form feature allocation
#' @param theta value of theta in product-form feature allocation
#' @param lambda Poisson hyperparameter 
#' @param n dimension of the sample to generate
#' 
#' @return list: $features contains the simulated features for each customer,
#' $num_new contains the number of new features selected for each customer
#' $counts contains the counts for the observed features
#' 
#' @export
rPoissonBB <- function(alpha, theta, lambda, n) {
    .Call(`_ProductFormFA_rPoissonBB`, alpha, theta, lambda, n)
}

#' Random generation from BB with NB(nstar,p) mixture
#' 
#' @param alpha value of alpha in product-form feature allocation
#' @param theta value of theta in product-form feature allocation
#' @param nstar Negative-Binomial hyperparameter (number of successes)
#' @param p Negative-Binomial hyperparameter (success probability)
#' @param n dimension of the sample to simulate
#' 
#' @return list: $features contains the simulated features for each customer,
#' $num_new contains the number of new features selected for each customer,
#' $counts contains the counts for the observed features
#' 
#' @export
rNegBinBB <- function(alpha, theta, nstar, p, n) {
    .Call(`_ProductFormFA_rNegBinBB`, alpha, theta, nstar, p, n)
}

#' Random generation from IBP with Gamma(a,b) mixture
#' 
#' @param alpha value of alpha in product-form feature allocation
#' @param theta value of theta in product-form feature allocation
#' @param a Gamma hyperparameter (shape)
#' @param b Gamma hyperparameter (rate)
#' @param n dimension of the sample to simulate
#' 
#' @return list: $features contains the simulated features for each customer,
#' $num_new contains the number of new features selected for each customer
#' $counts contains the counts for the observed features
#' 
#' @export
rGammaIBP <- function(alpha, theta, a, b, n) {
    .Call(`_ProductFormFA_rGammaIBP`, alpha, theta, a, b, n)
}

