# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_rbern <- function(n, prob) {
    .Call(`_ProductFormFA_cpp_rbern`, n, prob)
}

#' Negative Log-EFPF for the BB model with Poisson(lambda) mixture 
#' 
#' @param n dimension of the observed sample
#' @param counts vector of cardinalities for the observed features
#' @param pars pars[0] = value of alpha in product-form feature allocation,
#' pars[1] = value of s = theta + alpha in product-form feature allocation,
#' pars[2] =  value of lambda - Poisson hyperparameter
#' 
#' @return value of the negative logarithm of the EFPF for the sample of 
#' dimensionality n described by counts
#' 
neg_log_EFPF_PoissonBB <- function(n, counts, pars) {
    .Call(`_ProductFormFA_neg_log_EFPF_PoissonBB`, n, counts, pars)
}

#' Negative Log-EFPF for BB with NB(n0,p) mixture 
#' 
#' @param n dimension of the observed sample
#' @param counts vector of cardinalities for the observed features
#' @param pars pars[0] = value of alpha in product-form feature allocation,
#' pars[1] = value of s = theta + alpha in product-form feature allocation,
#' pars[2] = value of n0 - NB hyperparameter, first
#' pars[3] = value of p - NB hyperparameter, second
#' 
#' @return value of the negative logarithm of the EFPF for the sample of 
#' dimensionality n described by counts
#' 
neg_log_EFPF_NegBinBB <- function(n, counts, pars) {
    .Call(`_ProductFormFA_neg_log_EFPF_NegBinBB`, n, counts, pars)
}

#' Negative Log-EFPF for IBP with Gamma(a,b) mixture
#' 
#' @param n dimension of the observed sample
#' @param counts vector of cardinalities for the observed features
#' @param pars pars[0] = value of alpha in product-form feature allocation,
#' pars[1] = value of s = theta + alpha in product-form feature allocation,
#' pars[2] =  value of a - Gamma hyperparameter,
#' pars[3] =  value of b - Gamma hyperparameter
#' 
#' @return value of the negative logarithm of the EFPF for the sample of 
#' dimensionality n described by counts
#' 
neg_log_EFPF_GammaIBP <- function(n, counts, pars) {
    .Call(`_ProductFormFA_neg_log_EFPF_GammaIBP`, n, counts, pars)
}

stable_sum_M_all_gamma_IBP <- function(alpha, theta, m, only_last, n) {
    .Call(`_ProductFormFA_stable_sum_M_all_gamma_IBP`, alpha, theta, m, only_last, n)
}

#' Random generation from BB with Poisson(lambda) mixture
#' 
#' @param alpha value of alpha in product-form feature allocation
#' @param theta value of theta in product-form feature allocation
#' @param lambda Poisson hyperparameter 
#' @param n dimension of the sample to generate
#' 
#' @return list: $features contains the simulated features for each customer,
#' $num_new contains the number of new features selected for each customer
#' $counts contains the counts for the observed features
#' 
#' @export
#' 
rPoissonBB <- function(alpha, theta, lambda, n) {
    .Call(`_ProductFormFA_rPoissonBB`, alpha, theta, lambda, n)
}

#' Random generation from BB with NB(n0,mu0) mixture
#' 
#' @param alpha value of alpha in product-form feature allocation
#' @param theta value of theta in product-form feature allocation
#' @param n0 hyperparameter "n0" of NB(n0,mu0) for N
#' @param mu0 hyperparameter "mu0" of NB(n0,mu0) for N
#' @param n dimension of the sample to simulate
#' 
#' @return list: $features contains the simulated features for each customer,
#' $num_new contains the number of new features selected for each customer,
#' $counts contains the counts for the observed features
#' 
#' @export
#' 
rNegBinBB <- function(alpha, theta, n0, mu0, n) {
    .Call(`_ProductFormFA_rNegBinBB`, alpha, theta, n0, mu0, n)
}

#' Random generation from IBP with Gamma(a,b) mixture
#' 
#' @param alpha value of alpha in product-form feature allocation
#' @param theta value of theta in product-form feature allocation
#' @param a hyperparameter "a" of Gamma(a,b) for gamma
#' @param b hyperparameter "b" of Gamma(a,b) for gamma
#' @param n dimension of the sample to simulate
#' 
#' @return list: $features contains the simulated features for each customer,
#' $num_new contains the number of new features selected for each customer
#' $counts contains the counts for the observed features
#' 
#' @export
#' 
rGammaIBP <- function(alpha, theta, a, b, n) {
    .Call(`_ProductFormFA_rGammaIBP`, alpha, theta, a, b, n)
}

