# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Buffet procedure gamma IBP
#' 
#'
#' @export
buffet_gamma_IBP <- function(alpha, theta, n, a, b) {
    .Call(`_ProductFormFA_buffet_gamma_IBP`, alpha, theta, n, a, b)
}

p_kmn_all_gamma_IBP <- function(alpha, theta, m, n, b) {
    .Call(`_ProductFormFA_p_kmn_all_gamma_IBP`, alpha, theta, m, n, b)
}

p_kmn_gamma_IBP <- function(alpha, theta, m, n, b) {
    .Call(`_ProductFormFA_p_kmn_gamma_IBP`, alpha, theta, m, n, b)
}

buffet_negbin_BB <- function(alpha, theta, n, nstar, p) {
    .Call(`_ProductFormFA_buffet_negbin_BB`, alpha, theta, n, nstar, p)
}

p_kmn_all_negbin_BB <- function(alpha, theta, m, n, p) {
    .Call(`_ProductFormFA_p_kmn_all_negbin_BB`, alpha, theta, m, n, p)
}

p_kmn_negbin_BB <- function(alpha, theta, m, n, p) {
    .Call(`_ProductFormFA_p_kmn_negbin_BB`, alpha, theta, m, n, p)
}

buffet_poiss_BB <- function(alpha, theta, n, lambda) {
    .Call(`_ProductFormFA_buffet_poiss_BB`, alpha, theta, n, lambda)
}

buffet_poiss_BB_initial_sample <- function(alpha, theta, m, n, counts, lambda) {
    .Call(`_ProductFormFA_buffet_poiss_BB_initial_sample`, alpha, theta, m, n, counts, lambda)
}

mean_kmn_all_poiss_BB <- function(alpha, theta, m, n, lambda) {
    .Call(`_ProductFormFA_mean_kmn_all_poiss_BB`, alpha, theta, m, n, lambda)
}

mean_kmn_poiss_BB <- function(alpha, theta, m, n, lambda) {
    .Call(`_ProductFormFA_mean_kmn_poiss_BB`, alpha, theta, m, n, lambda)
}

cpp_rbern <- function(n, prob) {
    .Call(`_ProductFormFA_cpp_rbern`, n, prob)
}

